apiVersion: v1
kind: Pod
metadata:
  name: drud-cli-metrics
  labels:
    app: drud_cli_metrics
spec:
  containers:
    - name: drud-cli-metrics-server
      image: randyfay/drud_cli_metrics:0.1.1
      args:
        - "-http=0.0.0.0:80"
#        - "-health=0.0.0.0:81"
#        - "-secret=secret"
      ports:
        - name: http
          containerPort: 80
#        - name: health
#          containerPort: 81
      resources:
        limits:
          cpu: 0.2
          memory: "10Mi"
    volumeMounts:
    - mountPath: /var/lib/sqlite3
      name: sqlite3-db
  volumes:
  - name: sqlite3-db
    emptyDir: {}
