apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drud-cli-metrics-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drud-cli-metrics
        track: stable
    spec:
      containers:
        - name: drud-cli-metrics-container
          image: randyfay/drud_cli_metrics:0.0.6
          args:
    #        - "-port=0.0.0.0:12345"
    #        - "-health=0.0.0.0:81"
    #        - "-secret=secret"
          ports:
            - name: http
              containerPort: 12345
    #        - name: health
    #          containerPort: 81
          resources:
            limits:
              cpu: 0.2
              memory: "10Mi"
          volumeMounts:
          - mountPath: /var/lib/sqlite3
            name: sqlite3-db
      volumes:
      - name: sqlite3-db
        # NOTE THAT hostPath cannot support more than one node
        hostPath:
          path: /var/lib/sqlite3
