kind: Service
apiVersion: v1
metadata:
  name: "drud-cli-metrics"
spec:
  selector:
    app: "drud-cli-metrics"
  ports:
    - protocol: "TCP"
      port: 12345
      targetPort: 12345
      nodePort: 30001
  type: NodePort
